### Home
GET http://localhost:3000/

###

### Get all todos
GET http://localhost:3000/todos

###

### Get one todo
GET http://localhost:3000/todos/1

###

### Add a todo
POST http://localhost:3000/todos
Content-Type: application/json

{
    "task": "Finish DM Assignment"
}

###

### Mark completed
PUT http://localhost:3000/todos/4

###

### Delete
DELETE http://localhost:3000/todos/4

###

### Performance Endpoint
GET http://localhost:3000/compute